# Generated by Django 5.0.1 on 2026-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Элемент плана',
                'verbose_name_plural': 'Элементы плана',
                'db_table': 'plan',
                'ordering': ['u_project', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В работе'), ('idle', 'Простой'), ('sleep', 'Заморожен'), ('my', 'Мой')], default='planned', max_length=20, verbose_name='Статус')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='project_logos/', verbose_name='Логотип')),
                ('structure_data', models.JSONField(blank=True, default=dict, verbose_name='Структура проекта (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер'), ('member', 'Участник'), ('viewer', 'Наблюдатель')], max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Участие в проекте',
                'verbose_name_plural': 'Участия в проектах',
                'db_table': 'project_membership',
                'ordering': ['project', '-role'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('range', models.IntegerField(default=0, verbose_name='Диапазон')),
                ('importance', models.IntegerField(default=0, verbose_name='Важность')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
                'ordering': ['-importance', 'name'],
            },
        ),
    ]
