# Generated by Django 5.2.10 on 2026-02-03 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='u_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='tasks.task', verbose_name='Задача'),
        ),
    ]
