# Generated by Django 5.0.1 on 2026-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В работе'), ('idle', 'Простой'), ('sleep', 'Заморожен'), ('finished', 'Завершен')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('member', 'Участник'), ('customer', 'Заказчик')], max_length=20, verbose_name='Роль'),
        ),
    ]
