# Generated by Django 5.0.1 on 2026-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status_alter_projectmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='global_x',
            field=models.FloatField(default=0, verbose_name='X в супер-структуре'),
        ),
        migrations.AddField(
            model_name='project',
            name='global_y',
            field=models.FloatField(default=0, verbose_name='Y в супер-структуре'),
        ),
    ]
