# Generated by Django 5.0.1 on 2026-02-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='task',
            name='previous_tasks',
            field=models.ManyToManyField(blank=True, related_name='next_tasks', to='tasks.task', verbose_name='Предыдущие задачи'),
        ),
    ]
