# Generated by Django 5.0.1 on 2026-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('tag', models.CharField(choices=[('planned_expense', 'Планируемый расход'), ('approved_expense', 'Утверждённый расход'), ('expected_income', 'Ожидаемый доход'), ('actual_income', 'Фактический доход')], max_length=50, verbose_name='Тег')),
                ('operation', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=20, verbose_name='Операция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Финансовая запись',
                'verbose_name_plural': 'Финансовые записи',
                'db_table': 'billing',
                'ordering': ['-date'],
            },
        ),
    ]
