# Generated by Django 5.0.1 on 2026-02-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='billing',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='billing_entries', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
