# Generated by Django 5.2.10 on 2026-02-03 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='billing_entries', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
