# Generated by Django 5.0.1 on 2026-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='global_x',
            field=models.FloatField(default=0, verbose_name='X в супер-структуре'),
        ),
        migrations.AddField(
            model_name='user',
            name='global_y',
            field=models.FloatField(default=0, verbose_name='Y в супер-структуре'),
        ),
        migrations.AlterField(
            model_name='groupusers',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('guest', 'Guest')], max_length=50, unique=True, verbose_name='Название группы'),
        ),
    ]
