# Generated by Django 5.0.1 on 2026-03-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_global_x_user_global_y_alter_groupusers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('bg-gradient-1', 'Ocean Blue'), ('bg-gradient-2', 'Sunset Orange'), ('bg-gradient-3', 'Purple Dream'), ('bg-gradient-4', 'Forest Green'), ('bg-gradient-5', 'Night Sky'), ('bg-gradient-6', 'Cherry Blossom'), ('bg-gradient-7', 'Cosmic Fusion'), ('bg-gradient-8', 'Deep Sea'), ('bg-gradient-9', 'Tropical Sunrise'), ('bg-gradient-10', 'Arctic Frost'), ('bg-gradient-11', 'Neon Lights'), ('bg-gradient-12', 'Golden Hour')], default='bg-gradient-1', max_length=50)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uk', 'Українська'), ('en', 'English')], default='ru', max_length=10)),
            ],
            options={
                'db_table': 'global_settings',
            },
        ),
        migrations.AlterModelOptions(
            name='groupusers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='groupusers',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('guest', 'Guest')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='global_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='global_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('blocked', 'Заблокирован'), ('pending', 'Ожидает подтверждения')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.groupusers'),
        ),
    ]
