# Generated by Django 5.0.1 on 2026-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_globalsettings_alter_groupusers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light (Светлая)'), ('bg-gradient-1', 'Ocean Blue'), ('bg-gradient-2', 'Sunset Orange'), ('bg-gradient-3', 'Purple Dream'), ('bg-gradient-4', 'Forest Green'), ('bg-gradient-5', 'Night Sky'), ('bg-gradient-6', 'Cherry Blossom'), ('bg-gradient-7', 'Cosmic Fusion'), ('bg-gradient-8', 'Deep Sea'), ('bg-gradient-9', 'Tropical Sunrise'), ('bg-gradient-10', 'Arctic Frost'), ('bg-gradient-11', 'Neon Lights'), ('bg-gradient-12', 'Golden Hour')], default='light', max_length=50),
        ),
    ]
