# Generated by Django 5.2.10 on 2026-02-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('url_drive', models.URLField(blank=True, max_length=500, verbose_name='URL диска')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('update_date', models.DateField(blank=True, null=True, verbose_name='Дата обновления')),
                ('change_comment', models.TextField(blank=True, verbose_name='Комментарий к изменению')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступы',
                'db_table': 'access',
                'ordering': ['-created_at'],
            },
        ),
    ]
