# Generated by Django 5.0.1 on 2026-02-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='amount',
        ),
    ]
